# Generated by Django 6.0.3 on 2026-04-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_engine', '0006_remove_weekly_flags_idx_wf_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention_log',
            name='escalation_level',
        ),
        migrations.RemoveField(
            model_name='weekly_flags',
            name='escalation_level',
        ),
        migrations.AddField(
            model_name='weekly_metrics',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
    ]
