# Generated by Django 6.0.3 on 2026-05-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_engine', '0007_remove_intervention_log_escalation_level_and_more'),
    ]

    operations = [
    ]
